alphagov/pay-nginx-proxy

ci-build.sh, defaults.sh, enable_location.sh, lua/set_uuid.lua, nginx.conf
Pay historically use X-Request-Id as our uuid header. This gets passed
to applications, which send it on to any upstream services. This is set
in every microservice we have. Rather than change them all to use
nginxId, enable passing in an arbitrary uuid var name. Defaults to
nginxId so shouldn’t effect current behaviour.
=> Enable setting UUID var name and passing in

ci-build.sh, go.sh
In order to use  UKHomeOffice/docker-nginx-proxy as our nginx
container we need to be able to specifiy the logging format
to maiantain backwards compatibility with rest of platform.
This commit is Josh's work on custom log format, and I have added
a test showing how we can pass in our current format.
Need to check if host header would be set correctly by
upstream services
=> PP-2599 Custom logging format

README.md, defaults.sh, go.sh
##WHAT
Stops the container attempting to determine the region by making a call to the EC2 metadata service.
Requests to this endpoint will be blocked to ensure role based access on ECS based deployments where secrets management best practice is dependent on restricting access to the parameter store based on assigned roles. Services being able to access the EC2 metadata service are able to bypass this security restriction so this is blocked via iptables modifications on an ECS cluster host instance.
As such, the container is dependent on "AWS_REGION" as an environment variable, being passed to it.
=> [WIP] PP-2604 AWS Region is now passed as an environment variable

go.sh
Modifies the configuration of NGINX to allow nginx_status endpoint requests to also accept connections from the docker bridge networking interface.
A block of code in the go.sh file, enables the nginx_status endpoint in the event that a DISABLE_SYSDIG_METRICS environment variable is set with anything other than an empty string. This inserts a configuration block into the main NGINX configuration file drops any connection requests from anything other than 127.0.0.1
This PR adds the following configuration to the code block: 
`allow 172.17.0.1;`
=> PP-2600 check nginx status module is working

Dockerfile, go.sh
If we don't have a TLS key and certificate mounted into the container by
Docker, generate a selfsigned one ourselves.
=> PP-5070: Generate a selfsigned TLS cert if necessary

Dockerfile, README.md, ci-build.sh, go.sh, nginx.conf
Allow the default level of error logging ('error') to be overridden via an
environment variable, 'ERROR_LOG_LEVEL'.
=> Make the error log level configurable

README.md, enable_location.sh
This allows the number of requests (specified in the delay param) to be processed without delay. This defines the point at which, within the burst size, excessive requests are throttled to comply with the define rate limit.
See: https://www.nginx.com/blog/rate-limiting-nginx/
=> Adds support for optional Nginx "delay" rate limiting argument

README.md, defaults.sh, go.sh
This correctly sets the real ip of the request to that of the client when nginx is forwarded the request from a load balancer using the header specified by `real_ip_header`. 
This ensures features such as IP rate limiting operate on the client's IP address, not the load balancer's IP. `set_real_ip_from` ensures only trusted IPs (e.g. VPC cidr range) are able to specify the forwarded IP.
Corresponding config PR: https://github.com/alphagov/pay-infra/pull/2379
=> Configure forwarded for ip

Dockerfile, README.md, go.sh
Some ECS apps may want to specify a higher `CLIENT_BODY_BUFFER_SIZE`,
allow them to do this through environment variables.
=> PP-6483 Allow configurable body buffer size

Dockerfile
Upgrade alpine linux to 3.11.6. Our current pinned version is not
compatible with the community package (latest version) for aws-cli. This
is now needed as the package has been removed from `testing/edge`.
Relates to https://github.com/alphagov/pay-nginx-proxy/pull/35
With @rjbaker
=> PP-6483 Update alpine linux to 3.11.6

ci-build.sh, go.sh
This is a quick fix to escape the un-escaped Nginx variables being used for the proxy key configuration. The result when the go.sh was being processed resulted in the Nginx config being saved with an empty proxy key - so all static assets were being served from the same cache key. Whatever file was stored in the cache first will be the same file that is returned for every static asset requested by the browser. We obviously don't want this!
This should fix the problem by escaping the `$variables` in the go.sh script and result in Nginx having the correct variables stored in the config.
=> [PP-7082] Fix Unescaped Proxy Variables

.secrets.baseline, ci-build.sh
PP-7495 Replace bbc.co.uk in the tests
The ci tests have begun failing trying to proxy on to www.bbc.co.uk
returning a 421:Misdirected Request. Replace bbc.co.uk with our own
payment page www.payments.service.gov.uk.
The version of nginx has not changed and the tests were failing on the
main branch so we suspect this is down to a change on server(s) hosting
www.bbc.co.uk. We have created a story to investigate which captures our
intial thoughts https://payments-platform.atlassian.net/browse/PP-7679
with @dj-maisy
with @dj-maisy
We don't understand why it has started failing for the BBC and have created this story to investigate further https://payments-platform.atlassian.net/browse/PP-7679
=> PP-7495 Replace bbc.co.uk in the tests

Jenkinsfile
Description:
- As part of PP-7683 we are having Concourse pull from Dockerhub and pushing the images to ECR test. However for our current apps Concourse
listens for a new alpha-release tag on our Git repos to indicate that the corresponding Docker image has been pushed to Dockerhub. If we were
to listen simply on a new image in Dockerhub then we would have no way of extracting the Git commit SHA as there is no guarantee that the commit SHA
for the latest master corresponding to that image (e.g. whilst the image is being built a new master merge occurs). To solve this issue we add a step
in the Jenkins pipeline to tag the nginx-proxy repo so when a new alpha-release-* tag occurs we know that the corresponding Docker image has been pushed into Dockerhub.
=> PP-7683 - Add alpha release tag to repo after successful Jenkins build

Jenkinsfile
Description:
- The tag_and_capture_notes_commit_based.sh script passes in the $SERVICE_TO_TAG into git clone --bare "git@github.com:alphagov/pay-${SERVICE_TO_TAG}.git". But we are currently
passing in docker-nginx-proxy whilst the Git repo URL is pay-nginx-proxy. This PR fixes this error
=> PP-7683 - Update service name to match git tag script

Dockerfile
Description:
- Linux alpine package manager automatically drops older versions when a newer version is released. Since
1.16.1-r0 is released that means our current version of 1.16.0.r1 is dropped
- This PR fixes this and ensures our docker image can now be built
=> BAU - Update nginx naxsi version

Dockerfile
Previous to this change the latest version of the aws-cli was installed
from the edge repo. On the 5 April 2021 the latest version was rebuilt
against python 3.9. The Alpine base image that we use includes Python
3.8.8. The start up script for the latest aws-cli package places the
necessary python packages under
`/usr/lib/python3.9/site-packages/awscli` and the default Python path
being used in the Alpine base image does not include any python3.9
directories so it fails to start.
We'll want to upgrade our Alpine base image and subsequently the other
packages but for now this change pins the version of the aws-cli to
the last know version that works with our Alpine base image:
https://pkgs.alpinelinux.org/package/v3.13/community/x86_64/aws-cli
I noticed this whilst rebuilding nginx-proxy …
=> PP-7870 Pin aws-cli version

Dockerfile, http_xslt_filter.conf
This changes the following versions:
* Alpine to 3.14.1 (from 3.13.5)
* Nginx to 1.20.1 (from 1.16.1)
It would be a good idea to test this manually to verify that the NAXSI rules are still working as intended.
=> [PP-8500] Bump Alpine and Nginx Versions

Dockerfile
This bumps Alpine to 3.14.3 from 3.14.1 and updates the associated Nginx packages.
Updating through 3.14.2 addresses the following OpenSSL vulnerabilities:
- CVE-2021-3711
- CVE-2021-3712
The update to 3.14.3 also addresses the following vulnerabilities:
- CVE-2020-25125 (for GnuPG)
- CVE-2021-22945 (for cURL)
- CVE-2021-22946 (for cURL)
- CVE-2021-22947 (for cURL)
As well as numerous security fixes for busybox.
You can test build the new Dockerfile:
```sh
git checkout PP-8910_update_alpine_314
docker build -t govukpay/docker-nginx-proxy .
```
You can _even_ run it in test by deploying `govukpay/docker-nginx-proxy:3.14.3-test` as a sidecar for the app of your choice.
=> [PP-8910] Bump Alpine to 3.14.3

.github/dependabot.yml
Adds dependabot config for the alpine docker image. I think this repo previously had the older version of Dependabot running against it, and never got switched to the newer native version.
I've created the labels in the repo settings.
=> BAU: Add dependabot config

Dockerfile
The previous versions have been removed from the APK registry, so the image build is failing.
https://alpine.pkgs.org/3.15/alpine-main-x86_64/nginx-mod-http-naxsi-1.20.2-r1.apk.html
No changes to the actual code as far as I can see, just a new release.
=> BAU: Bump nginx alpine packages

.github/workflows/post-merge.yml
See ADR https://github.com/alphagov/pay-architecture/pull/49/files
=> BAU: Exclude Github Actions/Dependabot from post-merge worklow

Dockerfile, go.sh
- Increases proxy buffer size to 12k to allow services enter and view long text on ‘manage payment links’ pages in selfservice
- Bumps nginx modules to new versions
=> ZD#4989490 Increase buffer size

Dockerfile
Brings in security fixes for CVE-2022-41741 and CVE-2022-41742. See [http://nginx.org/en/CHANGES](http://nginx.org/en/CHANGES).
Team manual will be updated separately (along with the changes from https://github.com/alphagov/pay-nginx-forward-proxy/pull/50)
=> BAU Bump Nginx NAXSI packages

.github/dependabot.yml
Configure Dependabot updates for its Github Actions dependencies.
=> BAU: Add Dependabot config for Github Actions

Dockerfile
Bump nginx module releases, the current ones don't build anymore. Also fix the link to the team manual
=> PP-12308: Bump release package version of nginx modules

.github/dependabot.yml, Dockerfile
- Pins alpine base image to 3.19. We cannot bump to alpine 3.20 as there are incompatibilities with the aws-cli package. The aws-cli package maintainers recommend pinning to alpine 3.19 https://github.com/aws/aws-cli/issues/8342
- Bumps the naxsi packages manually in order to pick up the latest updates
=> PP-12694: Bump nginx modules and pin alpine to 3.19

.github/dependabot.yml, Dockerfile
aws-cli has been restored to alpine3.20
- Bumps nginx modules to v1.26.x
- Removes dependabot ignore
=> PP-12694: Update base image to alpine-3.20

Dockerfile
Noticed while we were updating the reverse proxy pipelines that the naxsi version has been updated and we can't build now. This bumps it to the latest patch version.
=> PP-11913: Update naxsi version

.github/workflows/run-tests.yml, nginx.conf
For unknown reasons we have curly braces surrounding our plain text logs.
The upstream home office version of this proxy creates a custom JSON format, I suspect there's been a misunderstanding when we implemented this.
Our log shipping code immediately removes any surrounding braces, and copes whether the log does or doesn't have the braces, so we can just get rid of them and remove one needless complexity in our logging config.
I will deploy this only to test and make sure splunk is correctly receiving the logs before allowing it to move to later envs.
=> PP-13322: Remove the needless braces surrounding otherwise plain text logs

.github/workflows/run-tests.yml, enable_location.sh, nginx.conf
- Updates logs format to KV format
Tested locally and below is the example log
>  server="localhost" dest_port="39000" dest_ip="172.18.0.16" src="172.18.0.1" src_ip="172.18.0.1" time_local="12/Feb/2025:19:05:28 +0000" protocol="HTTP/1.1" status="200" bytes_out="7583" bytes_in="27258" http_referer="https://localhost:39000/account/b0265cab2cc3439aa386682a670e3e8d/transactions?reference=&email=****&cardholderName=&lastDigitsCardNumber=&fromDate=&fromTime=&toDate=&toTime=&metadataValue=" http_user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36" nginx_version="1.26.2" http_x_forwarded_for="-" http_x_header="-" uri_query="reference=&email=****&cardholderName=&lastDigitsCardNumber=&fromDate=&fromTime=&toDate=&toTime=&me …
=> PP-13582 Change logs to KV format
